In [1]:
from google.colab import drive
drive.mount("/drive")

Mounted at /drive


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
Electric_data = pd.read_csv("/drive/My Drive/Colab Notebooks/Hamoye related/UCI_Electrical_grid_stability.csv")
Electric_grid_stability_dataframe = Electric_data.copy()
Electric_grid_stability_dataframe.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4      stab     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  0.049860  unstable

In [4]:
Electric_grid_stability_dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   tau1    10000 non-null  float64
 1   tau2    10000 non-null  float64
 2   tau3    10000 non-null  float64
 3   tau4    10000 non-null  float64
 4   p1      10000 non-null  float64
 5   p2      10000 non-null  float64
 6   p3      10000 non-null  float64
 7   p4      10000 non-null  float64
 8   g1      10000 non-null  float64
 9   g2      10000 non-null  float64
 10  g3      10000 non-null  float64
 11  g4      10000 non-null  float64
 12  stab    10000 non-null  float64
 13  stabf   10000 non-null  object 
dtypes: float64(13), object(1)
memory usage: 1.1+ MB


In [5]:
Electric_grid_stability_dataframe.describe()

tau1          tau2          tau3          tau4            p1  \
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.000000   
mean       5.250000      5.250001      5.250004      5.249997      3.750000   
std        2.742548      2.742549      2.742549      2.742556      0.752160   
min        0.500793      0.500141      0.500788      0.500473      1.582590   
25%        2.874892      2.875140      2.875522      2.874950      3.218300   
50%        5.250004      5.249981      5.249979      5.249734      3.751025   
75%        7.624690      7.624893      7.624948      7.624838      4.282420   
max        9.999469      9.999837      9.999450      9.999443      5.864418   

                 p2            p3            p4            g1            g2  \
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.000000   
mean      -1.250000     -1.250000     -1.250000      0.525000      0.525000   
std        0.433035      0.433035      0.433035      0.274256      0.274255   
min       -1.999891     -1.999945     -1.999926      0.050009      0.050053   
25%       -1.624901     -1.625025     -1.624960      0.287521      0.287552   
50%       -1.249966     -1.249974     -1.250007      0.525009      0.525003   
75%       -0.874977     -0.875043     -0.875065      0.762435      0.762490   
max       -0.500108     -0.500072     -0.500025      0.999937      0.999944   

                 g3            g4          stab  
count  10000.000000  10000.000000  10000.000000  
mean       0.525000      0.525000      0.015731  
std        0.274255      0.274255      0.036919  
min        0.050054      0.050028     -0.080760  
25%        0.287514      0.287494     -0.015557  
50%        0.525015      0.525002      0.017142  
75%        0.762440      0.762433      0.044878  
max        0.999982      0.999930      0.109403

In [6]:
Electric_grid_stability_dataframe.drop("stabf", axis=1)

tau1      tau2      tau3      tau4        p1        p2        p3  \
0     2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1     9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2     8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3     0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4     3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   
...        ...       ...       ...       ...       ...       ...       ...   
9995  2.930406  9.487627  2.376523  6.187797  3.343416 -0.658054 -1.449106   
9996  3.392299  1.274827  2.954947  6.894759  4.349512 -1.663661 -0.952437   
9997  2.364034  2.842030  8.776391  1.008906  4.299976 -1.380719 -0.943884   
9998  9.631511  3.994398  2.757071  7.821347  2.514755 -0.966330 -0.649915   
9999  6.530527  6.781790  4.349695  8.673138  3.492807 -1.390285 -1.532193   

            p4        g1        g2        g3        g4      stab  
0    -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347  
1    -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957  
2    -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471  
3    -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871  
4    -0.554305  0.797110  0.455450  0.656947  0.820923  0.049860  
...        ...       ...       ...       ...       ...       ...  
9995 -1.236256  0.601709  0.779642  0.813512  0.608385  0.023892  
9996 -1.733414  0.502079  0.567242  0.285880  0.366120 -0.025803  
9997 -1.975373  0.487838  0.986505  0.149286  0.145984 -0.031810  
9998 -0.898510  0.365246  0.587558  0.889118  0.818391  0.037789  
9999 -0.570329  0.073056  0.505441  0.378761  0.942631  0.045263  

[10000 rows x 13 columns]

In [7]:
Electric_grid_stability_dataframe.stabf = Electric_grid_stability_dataframe.stab
ones = Electric_grid_stability_dataframe.query("stab <= 0")
for x in Electric_grid_stability_dataframe.stabf:
  if x <= 0:
    Electric_grid_stability_dataframe.stabf.replace(x, 1, inplace=True)
  else:
    Electric_grid_stability_dataframe.stabf.replace(x, 0, inplace=True)
                                                    
Electric_grid_stability_dataframe.head()                                                    

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4      stab  stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347    0.0  
1 -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957    1.0  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471    0.0  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871    0.0  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  0.049860    0.0

In [8]:
features = Electric_grid_stability_dataframe.drop(columns=["stab", "stabf"])
features

tau1      tau2      tau3      tau4        p1        p2        p3  \
0     2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1     9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2     8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3     0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4     3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   
...        ...       ...       ...       ...       ...       ...       ...   
9995  2.930406  9.487627  2.376523  6.187797  3.343416 -0.658054 -1.449106   
9996  3.392299  1.274827  2.954947  6.894759  4.349512 -1.663661 -0.952437   
9997  2.364034  2.842030  8.776391  1.008906  4.299976 -1.380719 -0.943884   
9998  9.631511  3.994398  2.757071  7.821347  2.514755 -0.966330 -0.649915   
9999  6.530527  6.781790  4.349695  8.673138  3.492807 -1.390285 -1.532193   

            p4        g1        g2        g3        g4  
0    -1.723086  0.650456  0.859578  0.887445  0.958034  
1    -1.255012  0.413441  0.862414  0.562139  0.781760  
2    -0.920492  0.163041  0.766689  0.839444  0.109853  
3    -0.997374  0.446209  0.976744  0.929381  0.362718  
4    -0.554305  0.797110  0.455450  0.656947  0.820923  
...        ...       ...       ...       ...       ...  
9995 -1.236256  0.601709  0.779642  0.813512  0.608385  
9996 -1.733414  0.502079  0.567242  0.285880  0.366120  
9997 -1.975373  0.487838  0.986505  0.149286  0.145984  
9998 -0.898510  0.365246  0.587558  0.889118  0.818391  
9999 -0.570329  0.073056  0.505441  0.378761  0.942631  

[10000 rows x 12 columns]

In [9]:
label = Electric_grid_stability_dataframe["stabf"]
label

0       0.0
1       1.0
2       0.0
3       0.0
4       0.0
       ... 
9995    0.0
9996    1.0
9997    1.0
9998    0.0
9999    0.0
Name: stabf, Length: 10000, dtype: float64

In [10]:
from sklearn.preprocessing import StandardScaler 
ss = StandardScaler()
features_normalized = ss.fit_transform(features, label)

In [11]:
from sklearn.model_selection import train_test_split as tts
xtrain, xtest, ytrain, ytest = tts(features_normalized, label, test_size=.2, random_state=1)

In [12]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=1)
x_train, y_train = smote.fit_resample(xtrain, ytrain)

In [13]:
from sklearn.ensemble import RandomForestClassifier

x_train_rfc = x_train.copy()
y_train_rfc =  y_train.copy()
x_test_rfc = xtest.copy()
y_test_rfc = ytest.copy()

rfc = RandomForestClassifier()
rfc.fit(x_train_rfc, y_train_rfc)

RandomForestClassifier()

In [14]:
rfc_predict = rfc.predict(x_test_rfc)

In [15]:
# importing metrics for evaluation
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test_rfc, rfc_predict))
print(classification_report(y_test_rfc, rfc_predict))

[[1184  104]
 [  70  642]]
              precision    recall  f1-score   support

         0.0       0.94      0.92      0.93      1288
         1.0       0.86      0.90      0.88       712

    accuracy                           0.91      2000
   macro avg       0.90      0.91      0.91      2000
weighted avg       0.91      0.91      0.91      2000



In [18]:
from sklearn.ensemble import ExtraTreesClassifier

x_train_etcr = x_train.copy()
y_train_etcr =  y_train.copy()
x_test_etcr = xtest.copy()
y_test_etcr = ytest.copy()

etcr = ExtraTreesClassifier()
etcr.fit(x_train_etcr, y_train_etcr)

ExtraTreesClassifier()

In [19]:
print(etcr.feature_importances_)

[0.11526627 0.11684358 0.11429171 0.11812456 0.03884682 0.03933346
 0.03940772 0.03984324 0.09070625 0.09584758 0.09911331 0.09237551]


In [20]:
etcr_predict = etcr.predict(x_test_etcr)

In [21]:
print(confusion_matrix(y_test_etcr, etcr_predict))
print(classification_report(y_test_etcr, etcr_predict))

[[1222   66]
 [  80  632]]
              precision    recall  f1-score   support

         0.0       0.94      0.95      0.94      1288
         1.0       0.91      0.89      0.90       712

    accuracy                           0.93      2000
   macro avg       0.92      0.92      0.92      2000
weighted avg       0.93      0.93      0.93      2000



In [25]:
from xgboost import XGBModel

x_train_xgbm = x_train.copy()
y_train_xgbm =  y_train.copy()
x_test_xgmb = xtest.copy()
y_test_xgbm = ytest.copy()

xgbm = XGBModel()
xgbm.fit(x_train_xgbm, y_train_xgbm)

[16:10:59] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


XGBModel()

In [26]:
xgbm_predict = xgbm.predict(x_test_xgmb)

In [28]:
from sklearn.utils.fixes import sklearn
from sklearn.metrics import mean_absolute_error, mean_squared_error

print("mean absolute error: ", mean_absolute_error(y_test_xgbm, xgbm_predict))
msError = mean_squared_error(y_test_xgbm, xgbm_predict)
print("mean square error: ", msError)
print("Root mean squared error: ", np.sqrt(msError))

mean absolute error:  0.2548566555827856
mean square error:  0.091662520727333
Root mean squared error:  0.3027581885388618


In [29]:
from xgboost import XGBClassifier

x_train_xgbm = x_train.copy()
y_train_xgbm =  y_train.copy()
x_test_xgbm = xtest.copy()
y_test_xgbm = ytest.copy()

xgbm = XGBClassifier()
xgbm.fit(x_train_xgbm, y_train_xgbm)

XGBClassifier()

In [30]:
xgbm_predict = xgbm.predict(x_test_xgbm)

In [31]:
print(confusion_matrix(y_test_xgbm, xgbm_predict))
print(classification_report(y_test_xgbm, xgbm_predict))

[[1164  124]
 [  54  658]]
              precision    recall  f1-score   support

         0.0       0.96      0.90      0.93      1288
         1.0       0.84      0.92      0.88       712

    accuracy                           0.91      2000
   macro avg       0.90      0.91      0.90      2000
weighted avg       0.91      0.91      0.91      2000



In [32]:
from sklearn.utils.fixes import sklearn
from sklearn.metrics import mean_absolute_error, mean_squared_error

print("mean absolute error: ", mean_absolute_error(y_test_xgbm, xgbm_predict))
msError = mean_squared_error(y_test_xgbm, xgbm_predict)
print("mean square error: ", msError)
print("Root mean squared error: ", np.sqrt(msError))

mean absolute error:  0.089
mean square error:  0.089
Root mean squared error:  0.29832867780352595


In [33]:
from lightgbm import LGBMClassifier

x_train_lgbm = x_train.copy()
y_train_lgbm =  y_train.copy()
x_test_lgbm = xtest.copy()
y_test_lgbm = ytest.copy()

lgbm = LGBMClassifier()
lgbm.fit(x_train_lgbm, y_train_lgbm)

LGBMClassifier()

In [34]:
lgbm_predict = lgbm.predict(x_test_lgbm)

In [35]:
print(confusion_matrix(y_test_lgbm, lgbm_predict))
print(classification_report(y_test_lgbm, lgbm_predict))

[[1206   82]
 [  47  665]]
              precision    recall  f1-score   support

         0.0       0.96      0.94      0.95      1288
         1.0       0.89      0.93      0.91       712

    accuracy                           0.94      2000
   macro avg       0.93      0.94      0.93      2000
weighted avg       0.94      0.94      0.94      2000



In [36]:
print("mean absolute error: ", mean_absolute_error(y_test_lgbm, lgbm_predict))
msError = mean_squared_error(y_test_lgbm, lgbm_predict)
print("mean square error: ", msError)
print("Root mean squared error: ", np.sqrt(msError))

mean absolute error:  0.0645
mean square error:  0.0645
Root mean squared error:  0.2539685019840059
